name: Generate snake game

on:
  # execute every 12 hours
  schedule: 
    - cron: "* */12 * * *"
    
  # allows to manually run the job at any time
  workflow_dispatch:

    # run on every push on the master branch
  push:
    branches:
    - main

jobs:
  generate:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Snake Animation
      - uses: Sutil/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake2.svg
          snake_color: 'blue'

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

